/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dd_jni_StringCommon */

#ifndef _Included_com_dd_jni_StringCommon
#define _Included_com_dd_jni_StringCommon
#ifdef __cplusplus
extern "C" {
#endif
#undef com_dd_jni_StringCommon_JNI_METHOD_TYPE_0
#define com_dd_jni_StringCommon_JNI_METHOD_TYPE_0 0L
#undef com_dd_jni_StringCommon_JNI_METHOD_TYPE_1
#define com_dd_jni_StringCommon_JNI_METHOD_TYPE_1 1L
#undef com_dd_jni_StringCommon_JNI_METHOD_TYPE_2
#define com_dd_jni_StringCommon_JNI_METHOD_TYPE_2 2L
/*
 * Class:     com_dd_jni_StringCommon
 * Method:    printf
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_dd_jni_StringCommon_printf
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dd_jni_StringCommon
 * Method:    getNativeMsg
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dd_jni_StringCommon_getNativeMsg
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dd_jni_StringCommon
 * Method:    setNativeCount
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dd_jni_StringCommon_setNativeCount
  (JNIEnv *, jobject);

/*
 * Class:     com_dd_jni_StringCommon
 * Method:    callNativeSetCount
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_dd_jni_StringCommon_callNativeSetCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dd_jni_StringCommon
 * Method:    callNativeDiffType
 * Signature: (IFLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_dd_jni_StringCommon_callNativeDiffType
  (JNIEnv *, jobject, jint, jfloat, jstring, jint);

/*
 * Class:     com_dd_jni_StringCommon
 * Method:    callFatherFunction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dd_jni_StringCommon_callFatherFunction
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
